[package]
name = "mm_zmq"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
zmq = { workspace = true }

[dev-dependencies]
mm_binary = { workspace = true }

[features]
default = []
